#!/usr/bin/env python3
"""Renders LIVE_QUEUE.md from LIVE_QUEUE.json. Stack membership and land rules are maintained here (edit when stacks change)."""
import json, os, subprocess, sys
here = os.path.dirname(os.path.abspath(__file__)); root = os.path.dirname(here)
q = {(p['repo'].replace('growth-project-', ''), p['number']): p for p in json.load(open(os.path.join(root, 'LIVE_QUEUE.json')))}
B, M = 'backend', 'mobile'
STACKS = [
 ('1. Privacy (App Store and Play blocker)', [(B,611),(M,315)], 'Audit #611 FIX ROUND 7, then update-branch both and merge together; that publishes the policy (already covers Health Connect).'),
 ('2a. Fees (coach net payouts), was #627', [(B,681),(B,682),(B,683),(B,684),(B,685),(B,686),(M,321)], 'Rule 11: land as one (F2/F3 red by design; F1 unsafe alone). Deploy after #686. Mobile #321 merges with it.'),
 ('2b. Recurring packages, was #654 + mobile #334', [(B,678),(B,679),(B,680),(M,342),(M,343),(M,344)], 'Based on #686. Builder round on the unposted Sol draft 0/3/0 first. Owner adds Stripe setup_intent.succeeded before deploy.'),
 ('2c. Free trials, was #656', [(B,671),(B,672),(B,673),(M,338)], 'Green, inert until #673. Owner adds customer.subscription.trial_will_end before deploy. Mobile #338 after deploy.'),
 ('3. Coach wizard + Money, was #641 / #329 / #332', [(B,674),(B,676),(B,677),(B,675),(M,345),(M,346),(M,347),(M,348),(M,349),(M,350),(M,351),(M,340)], 'Backend first and deployed. Mobile #349/#350 red by design: land #348-#351 as one. #340 re-bases onto #351.'),
 ('4. Dunning + lockout, was #628 / #322', [(B,687),(B,688),(B,689),(B,690),(B,691),(M,352),(M,353),(M,354)], 'Backend pieces green; deploy after #691; then mobile.'),
 ('5. Health Connect day 1 (owner 10-03 18:42), was #317', [(M,359),(M,360),(M,361),(M,362),(M,363),(M,364)], 'Then a flag-flip PR FEATURE_WEARABLES_INGEST_POST=true + flag sync, clinic Android build (owner spend), Play Console declaration (owner), device pass.'),
 ('6. Approved, land with merge-only deltas', [(B,642),(B,652),(B,664),(M,312),(M,335)], 'Update-branch one at a time; two merge-only deltas each. #642 then the flag sync. #335 folds C-335-4 first.'),
 ('7. Programs, was #328', [(M,355),(M,356),(M,357),(M,358)], 'Green; backend already on main.'),
 ('8. Push delivery, was #648', [(B,692),(B,693)], 'Green. Confirm migration 20270307000000 absent from prod _prisma_migrations before deploy. FCM V1 key (owner) for Android.'),
 ('9. Builder work first', [(B,661),(M,339),(M,341),(M,331)], 'See section 4 C for findings. #331: apply patches/331-round3-wip.patch, then split.'),
 ('10. Roman, was #651', [(B,667),(B,665),(B,666),(B,668),(B,669),(B,670)], 'Builder writes the fix on #669 (recipe C3 in reports/B-SCHED-ROMAN-115.md). Land #668-#670 as one.'),
 ('11. Scheduling S-SCHED-2', [(B,634),(B,653),(M,365),(M,366),(M,367),(M,336)], '#634 needs a T4 builder refresh on main, then split. #653 rebases after #634. Mobile #365-#367 after #634 deploys.'),
 ('12. Annex and flags (not launch path)', [(B,655),(B,657),(B,658),(B,659),(B,660),(B,643),(B,650),(M,337)], '#657/#659/#660 over 3,000: builder refresh, then split. Flag flips only after their features are live.'),
]
lines = []
for title, prs, rule in STACKS:
    lines += [f'### {title}', '', rule, '', '| PR | Head (full sha) | Base | Lines | Draft | Merge state | Failing checks |', '|---|---|---|---|---|---|---|']
    for r, n in prs:
        p = q.get((r, n))
        if not p: lines.append(f'| {r} #{n} | (not fetched) | | | | | |'); continue
        fail = ', '.join(p['fail']) or 'none'
        lines.append(f"| {r} #{n} | `{p['head']}` | `{p['base']}` | {p['size']} | {'yes' if p['draft'] else 'no'} | {p['merge']} | {fail} |")
    lines.append('')
stamp = sys.argv[1] if len(sys.argv) > 1 else ''
hdr = [f'# Live queue (generated {stamp} PDT)', '',
 'Generated by tools/live_queue.sh + tools/live_queue_md.py. Re-run before acting; heads move. Lines = additions + deletions as GitHub',
 'reports them (lockfiles included, so a piece can read slightly higher than its size-rule count). "Failing checks" on stacked pieces',
 'can include stale entries from an earlier run at the same head (schema parity on #682/#685/#690 passed after close/reopen); confirm',
 'with `gh pr checks N`. Stacks are listed in launch-critical order (section 0.1 of HANDOFF_AGENT_116.md).', '']
open(os.path.join(root, 'LIVE_QUEUE.md'), 'w').write('\n'.join(hdr + lines))
print('ok')
